import type { Metadata } from "next";
import "./globals.css";

// === import font ===
import { IBM_Plex_Sans_Thai } from "next/font/google";
import Navigation from "./components/homepage/Navigation";
import Footer from "./components/homepage/Footer";

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
    subsets: ["thai"],
    weight: ["100", "200", "300", "400", "500", "600", "700"],
    variable: "--font-ibm-plex-sans-thai",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${ibmPlexSansThai.variable}`}>
            <body
                className={`antialiased bg-neutral-100 text-neutral-800 transition-all duration-300`}
            >
                <Navigation />
                <main>{children}</main>
                <Footer/>
            </body>
        </html>
    );
}
